//DO NOT EDIT THIS FILE -- YOU CAN CREATE A `credentials.js` WHICH IS GITIGNORED IF YOU DO NOT WANT TO USE ENV VARS

module.exports = {
    host     : process.env.MYSQL_HOST,
    user     : process.env.MYSQL_USER,
    password : process.env.MYSQL_PASSWORD,
    database : process.env.MYSQL_DATABASE
}